import logo from './logo-text.png'
import userDefaultImage from './icon-user-default.png'
import close from './close.svg'
import menu from './menu.svg'
import pos from './pos.jpg'
import allCategories from './categories/all.png'
import payment from './payments.svg'
import emptyCart from './empty_cart.svg'
import logoFull from './logo-full.png'
export {logo, userDefaultImage, close, menu, pos, allCategories, payment, emptyCart, logoFull}